### ISSUE TITLE
Support for the HxM Smart?

### ISSUE THREAD

**Issue by KK4BitsPerSecond** [uwburn/cardia#1]
Whats the issue with supporting the Smart? I received one for Christmas and can pair it with my PC. I would love to be able to use this in some game streams. 

I'm willing to help with it, I just don't know where to start. I wasn't sure if there was a reason.

**Comment by uwburn** [comment]
The current implementation is based on opening a serial port over the bluetooth link (Serial Port Profile), and then dealing with the underlying protocol.
Bluetooth 4 added several profiles for dedicated purposes, one of them is the HRM profile. Supporting the HRM profile should allow using (in theory) all BT 4.0 heart rate monitors, not just HxM.
The approach is a little bit different than the current one, as the support for BT 4.0 has to be present in the operating system to use the dedicated API. This means that only Windows 8.1 and later are supported.

I modified the code a while ago to lay down a base implementation, i should push the branch here.

The base problem is i don't have a BT 4.0 HRM to test with. I will let you know when the branch is up, if you wanna try to hack it out.

**Comment by KK4BitsPerSecond** [comment]
I can certainly give it a try.

**Comment by uwburn** [comment]
I committed the BT_Smart branch 3c4fca0c91b335dae0e85258d2d16ab8f6ce0cc8 with the temptative support to BT smart. Let me know if you find out something.

**Comment by KK4BitsPerSecond** [comment]
Sorry, I actually haven't had the chance to try it yet. University has been keeping me busy. Should have some time in a few weeks. Its on my to do list!

**Comment by uwburn** [comment]
Main discussion about BT smart is in #3. I'm closing this.

**Comment by uwburn** [comment]
Please checkout #3 for updated version, discussion there.
