### ISSUE TITLE
CMS 50D+

### ISSUE THREAD

**Issue by veanome** [uwburn/cardia#10]
Have you looked at all into implementing the Contec CMS 50D+? It's one of the cheaper versions of CMS 50E. I would imagine that CMS 50D+ would be somewhat easier to implement since it already supports CMS 50E.

Great work!

**Comment by uwburn** [comment]
Have you tried out with the CMS 50E profile to see if it works? Contec doesn't release any info about their protocols, so the only way to know is try out, the CMS50E support was reverse engineered by guessing out the message content.

**Comment by veanome** [comment]
I did try it out, I kept getting the error that no device was found

**Comment by uwburn** [comment]
A recording of the communication would be needed then... when the device is connected to your pc, is it considered as a serial port device?

**Comment by veanome** [comment]
Yes sir, when I connect the device to my PC I see it either in COM3 or COM4 under Device Manager.
