### ISSUE TITLE
Polar H10 support

### ISSUE THREAD

**Issue by Siecje** [uwburn/cardia#11]
I have a Polar H10. What would it take to support another device? I might be able to work on it.

**Comment by uwburn** [comment]
It should be already supported, as it is a BT Smart/LE device, You just need to use the latest version.

**Comment by Siecje** [comment]
I have it set on Bluetooth Smart HRP.

I'm using version `1.1.6588.32252` which I downloaded from the releases page.

When I select Start it says 

`Bluetooth HRP device initialization failed` at the bottom of the window.

**Comment by Siecje** [comment]
Okay after restarting and trying a couple times it works!! 

The README should list the Polar H10 as supported.

**Comment by uwburn** [comment]
Ok, thank you for the feedback!
