### ISSUE TITLE
Failed to Start Logger

### ISSUE THREAD

**Issue by alexbnieto** [uwburn/cardia#13]
Using Polar H10 with Cardia works great!

However when enabling log, I receive the error "Failed to start logger".

**Comment by uwburn** [comment]
I will look into it, admittedly i never tested logs with BT Smart devices.

**Comment by uwburn** [comment]
Should be fixed, please use [v1.1.0.1 Main](https://github.com/uwburn/cardia/releases/tag/v1.1.0.1_main).
