### ISSUE TITLE
XML Logging Error on Stop using Bluetooth HRP Device

### ISSUE THREAD

**Issue by alexbnieto** [uwburn/cardia#14]
Hello, 

Just tried out the logging using BT device on 1.1.0.1. Error occurs when STOP is pressed using XML format. 

Attached is the handled exception.

[xml_stop_log.txt](https://github.com/uwburn/cardia/files/1800816/xml_stop_log.txt)

**Comment by uwburn** [comment]
Whoops, XML Logger was still broken, try out [v1.1.0.2](https://github.com/uwburn/cardia/releases/tag/v1.1.0.2_main).
