### ISSUE TITLE
UDP Packet

### ISSUE THREAD

**Issue by SimWorld-code** [uwburn/cardia#17]
Dear,

I had a look to your nice project to receive polar H7 signal.
I would be very interested to get a new feature on the application that send the heart rate signal on UDP in order to use it in an other application.
Could you answer via alex@rssimmonaco.com ?
We would be very happy to pay the development time in order to get this new feature.

Regards
Alex

**Comment by uwburn** [comment]
Answered via mail.

Thanks for the interest in my project!
