### ISSUE TITLE
versions that support the HxM smart don't seem to work on Win7

### ISSUE THREAD

**Issue by rayanisran** [uwburn/cardia#20]
Any way to resolve this? I opened up one of the smart .sln files and I was missing a bunch of dependencies.. which I couldn't find. I'm hoping there is some fix because I can't upgrade to Win10 on this laptop :|

**Comment by uwburn** [comment]
HxM Smart requires BT Smart, that Win 7 doesn't support. To use BT Smart you must be on Win 8.1 or above, no way around this.

On Win 7 you can use the non-Smart version of Zephyr HxM.

**Comment by uwburn** [comment]
Stale.
