### ISSUE TITLE
Polar H10 broke with 1.2.0.0

### ISSUE THREAD

**Issue by ardittristan** [uwburn/cardia#21]
On version 1.1.0.2 my Polar H10 works fine, but with 1.2.0.0 I get Bluetooth HRP device initialization failed.

log: https://pastebin.com/F61Gn17Y

**Comment by uwburn** [comment]
Hello, from the logs appears that you changed the characteristic setting to 1, you shouldn't need to on the H10.

1. Check that the device is paired before starting Cardia
2. Check that the device is selected in Cardia and characteristic is 0
3. Start and wait till it times out
4. If it complains about an error in configuring the device as soon as you hit start, close and restart Cardia, sometimes Windows API seems to remain in unclear state after failed attempts to start the communications
