### ISSUE TITLE
Polar H7  no working with Bluetooth Smart HRP

### ISSUE THREAD

**Issue by BPRking** [uwburn/cardia#22]
my polar H7 no working with Bluetooh smart HRP, that say Bluetooth HRP Devide Not Transmitting but in my Phone it working perfect

**Comment by uwburn** [comment]
Hello, i suggest you to read the comments on #3, everything useful has already been discussed there.

I haven't tested Cardia with latest Windows updates yet, i hope they didnt "touched" the API again.

**Comment by uwburn** [comment]
Stale.
