### ISSUE TITLE
connection between cardia and modern arm-band

### ISSUE THREAD

**Issue by R-power** [uwburn/cardia#28]
dears,
this i not an issue.
it is a question

the last 1.2 version cardia (on W10 last update) may work with these recent ARM-HRM ?

polar-OH1
https://www.runnerinn.com/corsa/polar-oh1-ohr-sensor/137086981/p?utm_source=google_products&utm_medium=merchant&id_producte=8290090&country=it&gclid=CjwKCAjwwMn1BRAUEiwAZ_jnEmnwDf3AHvAHqVLz5EzjHQ6HM70h8bQd_21DZJyYQv74UKX9r1s2nRoCHhgQAvD_BwE&gclsrc=aw.ds

wahoo ticker fit
https://www.probikeshop.it/braccialetto-cardio-wahoo-tickr-fit/149505.html?gclid=CjwKCAjwwMn1BRAUEiwAZ_jnEjXhF2fls_zLSQzotDm8VgFbWIx9QynRCYYd6eMQpv_FcC2yFlOH2BoCurcQAvD_BwE&gshop=IT&ef_id=CjwKCAjwwMn1BRAUEiwAZ_jnEjXhF2fls_zLSQzotDm8VgFbWIx9QynRCYYd6eMQpv_FcC2yFlOH2BoCurcQAvD_BwE:G:s

and Cardia has compatibilty with recent smarwatches with integrated HRM ?
if yes what brand and model ?

thx a lot for support
ivo

**Comment by uwburn** [comment]
Hello, both of them _should_ be compatible. I don't have experience with any of them, but Polar devices always behaved pretty well with Cardia, while some time ago a user testing out a Wahoo was unable to get it to work.

Hope it helps!

**Comment by uwburn** [comment]
Stale.
