### ISSUE TITLE
Zephyr HxM  not transmitting on serial port 

### ISSUE THREAD

**Issue by SubterraNetwork** [uwburn/cardia#32]
Hey, 

I downloaded Cardia for a stream. I bought the Zephyr HxM for the cardia. I connected the Zephyr to my pc's bluetooth.  I started cardia but I kept getting "Zephyr HxM not transmitting on serial port COM1. COM4 and COM5 did not work either.  I don't really know anything about this. Can somebody help me?

Appreciate it

**Comment by uwburn** [comment]
Hello, check out what version you Zephyr is, as there are two:

- The original one, going through serial port profile
- The Smart one, going through heart rate profile

If it's the second don't use the zephy device entry, use HRP device entry and it will work.

**Comment by uwburn** [comment]
Stale.
