### ISSUE TITLE
Zephyr HxM not pairing with cardia

### ISSUE THREAD

**Issue by iamsolucid** [uwburn/cardia#36]
Trying to pair my HxM with cardia and it's not connecting on either the "Bluetooth Smart HRP" option or the zephyr device option. 
the HxM is connected to windows 10 and shows "paired" on the Bluetooth device lists.

![image](https://user-images.githubusercontent.com/73263208/96807806-78cbe900-13e5-11eb-9f4b-1fb6d3dacf42.png)
![image](https://user-images.githubusercontent.com/73263208/96807822-841f1480-13e5-11eb-88d6-a40865b892ed.png)
![image](https://user-images.githubusercontent.com/73263208/96807874-a1ec7980-13e5-11eb-82c1-4532a283975c.png)

all serial port COMs are empty (1-6)

**Comment by iamsolucid** [comment]
Wanted to add. On the Bluetooth Smart HRP configuration page, there are no other devices that I can choose from. The only option is Windows.devices.enumeration.device.inform??

**Comment by uwburn** [comment]
You whould really check out what version of Zephyr you have: https://www.zephyranywhere.com/system/hxm

If it's the BT version you whould use the dedicated Zephyr device in Cardia, if it's the Smart version you should use Bluethoot Smart HRP device in Cardia.

If it's the BT version emulating a serial port, you should check what serial port is being served by it, you should find this by checking serial ports properties in devices management.

Good luck!

**Comment by iamsolucid** [comment]
Hey I ordered a new zephyr and that seemed to work fine. Are there any arm
bands that work with this?

**Comment by iamsolucid** [comment]
i see, I ordered another zephyr and it worked fine! Since cardia works with the polar h7 and h10 is it possible that it would also work with the polar OH1+ ? 
https://www.amazon.com/Polar-Optical-Heart-Sensor-Bluetooth/dp/B07PM4P2RR/ref=sr_1_4?crid=18LCH4XQ189IG&dchild=1&keywords=polar+armband+monitor&qid=1603641142&sprefix=polar+arm+band%2Celectronics%2C299&sr=8-4

**Comment by uwburn** [comment]
Nice to see it works!

As for the OH1, it should be using Bluethoot HR Profile, if it's so i should work.

**Comment by mix3d** [comment]
Also related to #32

**Comment by uwburn** [comment]
Stale.
