### ISSUE TITLE
RealTime

### ISSUE THREAD

**Issue by Straconis** [uwburn/cardia#4]
It appears the BPM is reading an average.  Is there a way to get it to display real time bpm for things like jump scares?

**Comment by uwburn** [comment]
The average might be calculated by the HRM itself. I also coded a smoothing function (it could be useful for some devices) but currently is already disabled and not user accessible.

**Comment by Straconis** [comment]
I'm running the Zephyr HxM that the software indicated to use if you're not using the CMS 50.
