### ISSUE TITLE
Connecting Polar H10

### ISSUE THREAD

**Issue by Jetstar77** [uwburn/cardia#42]
Hey Guys
![Polar error](https://user-images.githubusercontent.com/91405030/134795514-033bc7d3-803f-4590-a484-f06b4f79a03b.png)

Would love to be able to use this software on my stream, When I try to connect it says Bluetooth HRP device initialization failed. Any thoughts?

**Comment by DesignThinkerer** [comment]
You might want to try again, mine worked fine

**Comment by uwburn** [comment]
Prably related to usual BtSmart HRP issues.
