### ISSUE TITLE
Windows 11 support (dev)

### ISSUE THREAD

**Issue by vladjester2020** [uwburn/cardia#43]
I updated to Windows 11. I tried connecting my Bluetooth Smart HRP and Cardia still searching. My Bluetooth Smart HRP still connecting on my PC with Bluetooth USB Driver. Maybe something need fix with new OS Windows 11.

[cardia_2021-12-26.log](https://github.com/uwburn/cardia/files/7796563/cardia_2021-12-26.log)
g

**Comment by uwburn** [comment]
Probably related to usual BtSmart HRP issues.

I will try it on Windows 11 i i have the chance.

**Comment by uwburn** [comment]
Confirmed working on Windows 11.
