### ISSUE TITLE
Source code rebuild - windows 10 and VS2019

### ISSUE THREAD

**Issue by dbalamo** [uwburn/cardia#44]
Hi,

I'd like to build  your sources on a Windows 10 machine, using VS2019 (or later),
but I'm facing errors for an unresolved dependency in HRM project, for the assembly with ID "windows"
![build_error](https://user-images.githubusercontent.com/63041462/150835428-3ba1c4a1-3a0e-4835-98fb-2ff6a716f0b0.png)

Could you specify which SDK are required to build this source code?

Thank you

**Comment by uwburn** [comment]
That's not a normal dependency, as getting BT HRP in WinForm projects it's kinda hacky. I don't have VS installed right now and i don't recall exactly how was the required SDK called, but you can take a look at HRM.csproj and get an idea: 

https://github.com/uwburn/cardia/blob/1536609a0f861dc78b602bd0275683476449345b/HRM/HRM.csproj#L61

**Comment by effgenesis** [comment]
This helped me. https://vblog11.rssing.com/chan-5517669/all_p4.html

**Comment by uwburn** [comment]
See #30.
