### ISSUE TITLE
ANT+ just need integration

### ISSUE THREAD

**Issue by sur1v** [uwburn/cardia#48]
Hello,

Thanks for this project, I really like it!

I just found this other project, also in C#, but that implements ANT+, looks like the job is done and we only need integration of the code.

https://github.com/julr/obs-ant-hrm

Thanks again!!!

**Comment by uwburn** [comment]
Duplicate of #9

**Comment by sur1v** [comment]
Sorry to comment on a closed issue, but this is not a duplicate IMHO. The cited is a feature request, this is code integration while they are similar and related is not the same job. Thanks!
